local SolarConquest = {

	["LR1"] = {
		["Id"] = 5823251788,
		["Name"] = "Silence Array",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 1,["Neutral"] = 1,},
		["Token"] = true,
		["TokenDiscard"] = true,
		["Transformant"] = "LR2",
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Inert in all zones. Transform a target fighter into this card.",
			["Type"] = "OnSummon",
			["Power"] = {{"Transform","Transformant"}},
			Target = "Single",
		},
		["Bio"] = "WRITEME",
	},
	
	["LR2"] = {
		["Id"] = 5823251788,
		["Name"] = "Intelligence Array",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 1,["Neutral"] = 1,},
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Reveal your opponent's hand.",
			["Type"] = "OnSummon",
			["Power"] = {{"RevealHand"}},
			Target = "Opponent",
		},
		["Bio"] = "WRITEME",
	},
	
	["LR3"] = {
		["Id"] = 5823251788,
		["Name"] = "Resource Array",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 3,["Neutral"] = 1,},
		["Token"] = true,
		["TokenDiscard"] = true,
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Inert in all zones. Draw a card.",
			["Type"] = "OnSummon",
			["Power"] = {{"Draw",1}},
			Target = "Ally",
		},
		["Bio"] = "WRITEME",
	},
	
	["LR4"] = {
		["Id"] = 5823251788,
		["Name"] = "Defence Array",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 2,["Neutral"] = 1,},
		["Token"] = true,
		["TokenDiscard"] = true,
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Inert in all zones. A target fighter loses 200 power.",
			["Type"] = "OnSummon",
			["Power"] = {{"Weaken",200}},
			Target = "Single",
		},
		["Bio"] = "WRITEME",
	},
	
	["LR5"] = {
		["Id"] = 5823251788,
		["Name"] = "Halting Array",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 4,["Neutral"] = 1,},
		["Token"] = true,
		["TokenDiscard"] = true,
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Inert in all zones. Lock a target fighter for 4 turns.",
			["Type"] = "OnSummon",
			["Power"] = {{"Lock",3}},
			Target = "Single",
		},
		["Bio"] = "WRITEME",
	},
	
	["LR6"] = {
		["Id"] = 5823251788,
		["Name"] = "Delay Array",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 1,["Neutral"] = 1,},
		["Token"] = true,
		["TokenDiscard"] = true,
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Inert in all zones. Lock a target fighter for 1 turn.",
			["Type"] = "OnSummon",
			["Power"] = {{"Lock",1}},
			Target = "Single",
		},
		["Bio"] = "WRITEME",
	},
	
	["LR7"] = {
		["Id"] = 5823251788,
		["Name"] = "Conjuring Array",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 5,["Neutral"] = 1,},
		["Token"] = true,
		["TokenDiscard"] = true,
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Inert in all zones. Summon a 500/400 Thoughtlich.",
			["Type"] = "OnSummon",
			["Power"] = {{"Lock",1}},
			Target = "Single",
		},
		["Bio"] = "WRITEME",
	},
	
	["LR8"] = {
		["Id"] = 5823251788,
		["Name"] = "Shield Array",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 1,},
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "A target fighter gains 50 health.",
			["Type"] = "OnSummon",
			["Power"] = {{"Heal",50}},
			Target = "Single",
		},
		["Bio"] = "WRITEME",
	},
	
	["LR9"] = {
		["Id"] = 5823251788,
		["Name"] = "Vitality Array",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 4, ["Red"] = 4, ["Neutral"] = 1,},
		["Token"] = true,
		["TokenDiscard"] = true,
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Inert in all zones. Give yourself three other Array cards.",
			["Type"] = "OnSummon",
			["Power"] = {{"RandomAdd",{"LR1","LR2","LR3","LR4","LR5","LR6","LR7","LR8","LR0","LRA","LRB","LRC","LRD","LRE"}},{"RandomAdd",{"LR1","LR2","LR3","LR4","LR5","LR6","LR7","LR8","LR0","LRA","LRB","LRC","LRD","LRE"}},{"RandomAdd",{"LR1","LR2","LR3","LR4","LR5","LR6","LR7","LR8","LR0","LRA","LRB","LRC","LRD","LRE"}},},
			Target = "Single",
		},
		--{"RandomAdd",{"LR1","LR2","LR3","LR4","LR5","LR6","LR7","LR8","LR9","LR0","LRA","LRB","LRC","LRD","LRE"}},
		["Bio"] = "WRITEME",
	},
	
	["LR0"] = {
		["Id"] = 5823251788,
		["Name"] = "Destruction Array",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Red",
		["Cost"] = {["Red"] = 2, ["Neutral"] = 1,},
		["Summon"] = "Thoughtlich", 
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Deal 200 damage to a target fighter.",
			["Type"] = "OnSummon",
			["Power"] = {{"Damage",250}},
			Target = "Single",
		},
		["Bio"] = "WRITEME",
	},
	
	["LRA"] = {
		["Id"] = 5823251788,
		["Name"] = "Transmutation Array",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 2, ["Neutral"] = 1,},
		["Token"] = true,
		["TokenDiscard"] = true,
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Inert in all zones. Swap the stats of a target fighter.",
			["Type"] = "OnSummon",
			["Power"] = {{"Swap",9999}},
			Target = "Single",
		},
		["Bio"] = "WRITEME",
	},
	
	["LRB"] = {
		["Id"] = 5823251788,
		["Name"] = "Construction Array",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 5, ["Neutral"] = 1,},
		["Token"] = true,
		["TokenDiscard"] = true,
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Inert in all zones. Each card you cast this turn costs a single Colourless stud less to cast.",
			["Type"] = "OnSummon",
			["Power"] = {{"Tax",-1}},
			Target = "Ally",
		},
		["Bio"] = "WRITEME",
	},
	
	["LRC"] = {
		["Id"] = 5823251788,
		["Name"] = "Counterspell Array",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 2, ["Neutral"] = 1,},
		["Token"] = true,
		["TokenDiscard"] = true,
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Inert in all zones. Reset the stats of all enemy fighters.",
			["Type"] = "OnSummon",
			["Power"] = {{"Reset"}},
			Target = "Opponent",
		},
		["Bio"] = "WRITEME",
	},
	
	["LRD"] = {
		["Id"] = 5823251788,
		["Name"] = "Paraselence Array",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 1, ["Red"] = 1,},
		["Token"] = true,
		["TokenDiscard"] = true,
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Inert in all zones. Reset the stats of all enemy fighters.",
			["Type"] = "OnSummon",
			["Power"] = {{"Reset"}},
			Target = "Opponent",
		},
		["Bio"] = "WRITEME",
	},
	
	["LRE"] = {
		["Id"] = 5823251788,
		["Name"] = "Endurance Array",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Blue",
		["Cost"] = {["Blue"] = 1,},
		["Token"] = true,
		["TokenDiscard"] = true,
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Inert in all zones. You gain 400 life.",
			["Type"] = "OnSummon",
			["Power"] = {{"Cost",400}},
			Target = "Opponent",
		},
		["Bio"] = "WRITEME",
	},
	
	["Thoughtlich"] = {
		["Id"] = 5823251788,
		["Name"] = "Thoughtlich",
		["Health"] = 500,
		["Power"] = 400,
		["Rarity"] = "Token",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Green",
		["Cost"] = {["Neutral"] = 0,},
		["Bio"] = [["Two lives overlapped into one body. What wonderful efficiency." --Ptenda]],
	},
	
	["Viscount of the Federation"] = {
		["Id"] = 5823251788,
		["Name"] = "Viscount of the Federation",
		["Health"] = 600,
		["Power"] = 200,
		["Rarity"] = "Common",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Red",
		["Cost"] = {["Neutral"] = 3,},
		["Token"] = true,
		["TokenDiscard"] = true,
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Whenever you cast an action that costs 8 or more total studs: This card gains 400 health and power.",
			["Type"] = "OnAllyCast",
			["Power"] = {{"Heal",400},{"Strengthen",400}},
			["Cost"] = 8,
			Target = "Self",
		},
		["Bio"] = "WRITEME",
	},
	
	["Spirit Seed"] = {
		["Id"] = 5823251788,
		["Name"] = "Spirit Seed",
		["Health"] = 0,
		["Power"] = 0,
		["Rarity"] = "Common",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Green",
		["Cost"] = {["Neutral"] = 1, ["Green"] = 3,},
		["Summonant"] = "Thoughtlich",
		["Plantant"] = "Spirit Seed",
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "Summon a 500/400 Thoughtlich. Plant this card into a target fighter. (Its owner gets a copy of it the next time it attacks.)",
			["Type"] = "OnSummon",
			["Power"] = {{"Summon","Summonant"},{"Encode","Plantant"}},
			Target = "Ally",
		},
		["Bio"] = [["I will remind you: Grass grows in dirt. Spirits grow in people." --Ptenda]],
	},
	
	["Aeonite Challenger"] = {
		["Id"] = 5823251788,
		["Name"] = "Aeonite Challenger",
		["Health"] = 1200,
		["Power"] = 400,
		["Rarity"] = "Uncommon",
		["AttackEffect"] = {"Magic", "Blue"},
		["Color"] = "Green",
		["Cost"] = {["Neutral"] = 3, ["Green"] = 6,},
		["Effect"] = {
			Name = "Syzygy's Sheen",
			Description = "During your end step, if a card is planted nto this card: All planted fighters gain 100 power.",
			["Type"] = "OnEnd",
			["Power"] = {{"Strengthen",100}},
			["Planted"] = true,
			Target = "Planted",
		},
		["Bio"] = "WRITEME",
	},

}
return  SolarConquest